name: CI & Required Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: app

      - name: Checkout Design System Peer Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: rtkelly13/design-system
          path: design-system

      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78d470a0d99e2e94e9b60d77f8045952f4 # v3.0.0
        with:
          version: 9

      - name: Setup Python & uv
        uses: astral-sh/setup-uv@f943869273c52e85a676ebf67645f7bb2a84b06a # v5.1.0
        with:
          version: "latest"

      - name: Build Design System Peer Repo
        run: |
          cd design-system
          pnpm install --no-frozen-lockfile
          pnpm build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Frontend Dependencies
        run: |
          cd app/frontend
          pnpm install --no-frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend Bundle
        run: |
          cd app/frontend
          pnpm build

      - name: Install Backend Dependencies
        run: |
          cd app/backend
          uv sync
